---
- hosts: all
  become: yes
  roles:
    - role: requirerole
      requirerole_owner: root
      requirerole_repos_private: []
      requirerole_repos_public:
        - repo: "https://github.com/gotansible/requirerole.git"
          subfolder: "defaults"
          fullname: "gotansible.subfolder-test"
          version: "master"

        - repo: "https://github.com/gotansible/requirerole.git"
          subfolder: ""
          fullname: "gotansible.requirerole-test"
          version: "master"
