---

- name: depend - debian install dependencies
  become_user: root
  apt:
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
    - git
    - curl
    - mercurial
  when: ansible_os_family == 'Debian'

