---

- name: ensure temporary download location
  file:
    state=directory
    path={{ requirerole_temp }}

- name: ensure destination location
  file:
    state=directory
    path={{ requirerole_destination }}
    owner={{ requirerole_owner }}
    group={{ requirerole_group }}

- name: checkout code to build dir - with key
  git:
    repo={{ item.repo }}
    version={{ item.version }}
    depth=1
    update=yes
    accept_hostkey=yes
    dest={{ requirerole_temp }}
    force=yes
    recursive=yes
    key_file={{ requirerole_keyfile }}
  with_items: "{{ requirerole_repos_private }}"

- name: checkout code to build dir - with key
  git:
    repo={{ item.repo }}
    version={{ item.version }}
    depth=1
    update=yes
    accept_hostkey=yes
    dest={{ requirerole_temp }}
    force=yes
    recursive=yes
  with_items: "{{ requirerole_repos_public }}"

- name: copy roles to final location
  command: cp -Rf {{ requirerole_temp }}/{{ item.folder }}/{{ subfolder }} {{ requirerole_destination }}/{{ item.fullname }}


